version: '2'
services:
    jaspertest-app:
        image: jaspertest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jaspertest-mysql:3306/jaspertest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jaspertest-mysql:
        extends:
            file: mysql.yml
            service: jaspertest-mysql
